# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstWindowdis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from signUpWin import Ui_MainWindow

class Ui_firstWindow(object):
    def setupUi(self, firstWindow):
        firstWindow.setObjectName("firstWindow")
        firstWindow.resize(3754, 1973)
        self.centralwidget = QtWidgets.QWidget(firstWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(510, 300, 151, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.signUpButton = QtWidgets.QPushButton(self.centralwidget)
        self.signUpButton.setGeometry(QtCore.QRect(210, 620, 121, 41))
        self.signUpButton.setObjectName("signUpButton")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setGeometry(QtCore.QRect(490, 150, 131, 41))
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.signInUpLabel = QtWidgets.QLabel(self.centralwidget)
        self.signInUpLabel.setGeometry(QtCore.QRect(270, 330, 291, 21))
        self.signInUpLabel.setObjectName("signInUpLabel")
        self.usernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameInput.setGeometry(QtCore.QRect(310, 470, 113, 22))
        self.usernameInput.setObjectName("usernameInput")
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setGeometry(QtCore.QRect(310, 500, 113, 22))
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.signInButton = QtWidgets.QPushButton(self.centralwidget)
        self.signInButton.setGeometry(QtCore.QRect(500, 480, 121, 41))
        self.signInButton.setObjectName("signInButton")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(230, 470, 71, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(230, 500, 71, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.ifItIsYourFirstTimeHereLabel = QtWidgets.QLabel(self.centralwidget)
        self.ifItIsYourFirstTimeHereLabel.setGeometry(QtCore.QRect(40, 620, 161, 31))
        self.ifItIsYourFirstTimeHereLabel.setObjectName("ifItIsYourFirstTimeHereLabel")
        firstWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(firstWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 3754, 26))
        self.menubar.setObjectName("menubar")
        firstWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(firstWindow)
        self.statusbar.setObjectName("statusbar")
        firstWindow.setStatusBar(self.statusbar)

        self.signUpButton.clicked.connect(self.signUpButtonPressed)

        self.retranslateUi(firstWindow)
        QtCore.QMetaObject.connectSlotsByName(firstWindow)

    def retranslateUi(self, firstWindow):
        _translate = QtCore.QCoreApplication.translate
        firstWindow.setWindowTitle(_translate("firstWindow", "MainWindow"))
        self.signUpButton.setText(_translate("firstWindow", "sign up"))
        self.welcomeLabel.setText(_translate("firstWindow", "Welcome!"))
        self.signInUpLabel.setText(_translate("firstWindow", "please sign in"))
        self.signInButton.setText(_translate("firstWindow", "sign in"))
        self.usernameLabel.setText(_translate("firstWindow", "username:"))
        self.passwordLabel.setText(_translate("firstWindow", "password:"))
        self.ifItIsYourFirstTimeHereLabel.setText(_translate("firstWindow", "If it is your first time here:"))

    def signUpButtonPressed(self):
        firstWindow.hide()
        self.signUpWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.signUpWindow)
        self.signUpWindow.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    firstWindow = QtWidgets.QMainWindow()
    ui = Ui_firstWindow()
    ui.setupUi(firstWindow)
    firstWindow.show()
    sys.exit(app.exec_())
