# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singUpWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2635, 1265)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signUpLabel = QtWidgets.QLabel(self.centralwidget)
        self.signUpLabel.setGeometry(QtCore.QRect(510, 170, 51, 41))
        self.signUpLabel.setObjectName("signUpLabel")
        self.createYourUsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.createYourUsernameLabel.setGeometry(QtCore.QRect(200, 410, 141, 31))
        self.createYourUsernameLabel.setObjectName("createYourUsernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(200, 540, 71, 21))
        self.passwordLabel.setObjectName("passwordLabel")
        self.newUserName = QtWidgets.QLineEdit(self.centralwidget)
        self.newUserName.setGeometry(QtCore.QRect(280, 450, 113, 22))
        self.newUserName.setObjectName("newUserName")
        self.newPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.newPassword.setGeometry(QtCore.QRect(270, 540, 113, 22))
        self.newPassword.setObjectName("newPassword")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(200, 450, 71, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.createYourPasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.createYourPasswordLabel.setGeometry(QtCore.QRect(200, 510, 141, 16))
        self.createYourPasswordLabel.setObjectName("createYourPasswordLabel")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(530, 540, 93, 28))
        self.confirmButton.setObjectName("confirmButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2635, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.confirmButton.clicked.connect(self.confirmPressed)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signUpLabel.setText(_translate("MainWindow", "sign up"))
        self.createYourUsernameLabel.setText(_translate("MainWindow", "create your username:"))
        self.passwordLabel.setText(_translate("MainWindow", "password:"))
        self.usernameLabel.setText(_translate("MainWindow", "username:"))
        self.createYourPasswordLabel.setText(_translate("MainWindow", "create your password:"))
        self.confirmButton.setText(_translate("MainWindow", "confirm"))

    def confirmPressed(self):
        print(self.newUserName.text())





if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

